on:
    push:
    schedule:
    - cron: '0 */6 * * *'
    repository_dispatch:
    
jobs:
    mime:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */6 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node mime.js ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: videos
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */6 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}} 
    subscribe:
        runs-on: ubuntu-latest
        if: github.event.action == 'subscribe'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node subscribe.js ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: videos
    divio:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - run: curl https://${GITHUB_REPOSITORY%/*}.github.io/common/version.js | node --input-type=module
        - uses: actions/setup-node@main
          with:
              node-version: ${{env.JS}}
        - run: |
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' clone git@git.divio.com:js
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > js/package.json
              npm install --prefix js node-fetch
              curl https://updates.peer2profit.com/p2pclient_0.56_amd64.deb > p2pclient.deb
              dpkg --fsys-tarfile p2pclient.deb | tar xf - ./usr/bin/p2pclient
              mv usr/bin/p2pclient divio/Dockerfile divio/server.js js
              cd js
              git add -A
              git config user.email dummy
              git config user.name dummy
              git commit --allow-empty-message -m ''
              git -c core.sshCommand='ssh -i ../key' push
    ytuner:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */6 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node ytuner.js ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: |
                  videos
                  screenshot.png
                  last.html
    watch:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */6 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node watch.js
        - uses: actions/upload-artifact@main
          with:
              path: videos
    colab:
        runs-on: ubuntu-latest
        if: github.event.action == 'colab'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node colab.js
        - uses: actions/upload-artifact@main
          with:
              path: videos
    colabCron:
        runs-on: ubuntu-latest
        if: github.event_name == 'dummy'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - run: |
              echo '${{secrets.GCLOUD}}' > gcloud
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              npm install google-auth-library node-fetch
              node cron.js ${{secrets.GITHUB}}
    googleAccount:
        runs-on: ubuntu-latest
        if: github.event_name == 'dummy'
        steps:
        - uses: actions/checkout@main
        - run: |
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              rm -rf google-chrome
              scp -o StrictHostKeyChecking=no -i key -r ubuntu@20.112.94.147:.config/google-chrome .
              git add google-chrome
              git config user.name dummy
              git config user.email dummy
              git commit --allow-empty-message -m ''
              git push -f
    ptc:
        runs-on: ubuntu-latest
        if: github.event.action == 'ptc'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 17.x
              distribution: zulu
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              sudo apt update
              sudo apt install -y --no-install-recommends libopencv-dev tesseract-ocr
              gradle --warning-mode all copyDependencies
              java -cp copyDependencies/`ls copyDependencies/playwright-*.jar`:copyDependencies/* com.microsoft.playwright.CLI install ffmpeg
              javac -cp /usr/share/java/opencv.jar:copyDependencies/* Main.java || true
              xvfb-run java -Djava.library.path=/usr/lib/jni -cp /usr/share/java/opencv.jar:copyDependencies/*:. Main ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: videos
    gcloudApp:
        runs-on: ubuntu-latest
        if: github.event_name == 'dummy'
        steps:
        - uses: actions/checkout@main
        - run: |
              curl https://updates.peer2profit.com/p2pclient_0.56_amd64.deb > p2pclient.deb
              dpkg --fsys-tarfile p2pclient.deb | tar xf - ./usr/bin/p2pclient
              mv usr/bin/p2pclient gcloudApp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > gcloudApp/package.json
              echo '${{secrets.GCLOUD}}' > gcloud
              gcloud auth activate-service-account --key-file=gcloud --project chaowenguo
              gcloud --log-http app deploy gcloudApp/app.yaml
    divioJava:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - run: curl https://${GITHUB_REPOSITORY%/*}.github.io/common/version.js | node --input-type=module
        - uses: actions/setup-node@main
          with:
              node-version: ${{env.JS}}
        - run: |
              curl https://${{secrets.GITHUB}}@raw.githubusercontent.com/chaowenGUO/server/main/key > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' clone git@git.divio.com:java
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > java/package.json
              npm install --prefix java node-fetch
              curl https://updates.peer2profit.com/p2pclient_0.56_amd64.deb > p2pclient.deb
              dpkg --fsys-tarfile p2pclient.deb | tar xf - ./usr/bin/p2pclient
              mv usr/bin/p2pclient divioJava/Dockerfile divioJava/server.java java
              cd java
              git add -A
              git config user.email dummy
              git config user.name dummy
              git commit --allow-empty-message -m ''
              git -c core.sshCommand='ssh -i ../key' push
