on:
    push:
    schedule:
    - cron: '0 */6 * * *'
    - cron: '0 */4 * * *'
    - cron: '0 6,18 * * *'
    - cron: '0 */2 * * *'
    - cron: '0 1 * * *'
    
jobs:
    mime:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */6 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node mime.js ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: videos
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB_TOKEN}} 
    subscribe:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 6,18 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node subscribe.js ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: videos
    ytuner:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 */4 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node ytuner.js ${{secrets.PASSWORD}}
        - uses: actions/upload-artifact@main
          with:
              path: |
                  videos
                  screenshot.png
                  last.html
    watch:
        runs-on: ubuntu-latest
        #if: github.event.schedule == '0 */2 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 17.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node watch.js
        - uses: actions/upload-artifact@main
          with:
              path: videos
