on:
    push:
    schedule:
    - cron: '0 */6 * * *'
    - cron: '0 1 * * *'
    
jobs:
    build:
        runs-on: ubuntu-latest
        #if: github.event.schedule == '0 */6 * * *'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-node@main
          with:
              node-version: 16.x
        - env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
              DEBUG: pw:api
          run: |
              npm install playwright-chromium
              npx playwright install ffmpeg
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/package.json > package.json
              xvfb-run node ha.js
        - uses: actions/upload-artifact@main
          with:
              path: videos
    clean:
        runs-on: ubuntu-latest
        if: github.event.schedule == '0 1 * * *'
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://${GITHUB_REPOSITORY%/*}.github.io/common/clean.py | python - ${{secrets.GITHUB}} 
